let fruits=["Apple","Grapes","Pear",74];
//console.log(fruits);
//console.log(fruits[4]);
fruits.push("Banana");
//console.log(fruits);
fruits.pop();
console.log(fruits);
fruits.unshift("Watermelon");
console.log(fruits);
fruits.pop(1);
console.log(fruits);
